### ISSUE TITLE
 Deep battery discharge

### ISSUE THREAD

**Issue by Mirinzana** [aver-ua/esphome-hybrid-inverter-2341#2]
This code is very useful, once the hardware was prepared it worked very well the first time it was turned on. I have a 4.2kw 24v powmr hybrid inverter, my problem is that when switched from inverter mode to line mode the battery continues to discharge as if there was a phantom load,in practice if set to 24 volts with everything off it dropped to 19Volt . I tested mine lifepo4 battery and holds a charge as per specifications. Would it be helpful to change the code so that it can only read data and not change configuration remotely? Also because using your mobile phone you can change important parameters involuntarily 
 by scrolling the screen with your finger
Thanks for your work
marco.

**Comment by aver-ua** [comment]
hi. I have also Powmr 4.2kw 24v model, but I don't have an issue you described.. it is very strange. 
my settings for Lifepo4 battery:
Bulk charging voltage: 28.4
Floating charging voltage: 27.2
Low DC cut-off voltage: 23

you can try configs from `src-nowr` folder (without write registers)

**Comment by Mirinzana** [comment]
Thanks for the reply, I have the same battery parameters, yes it's strange. I do as you advise. If everything works for you, as it seemed to me, perhaps it's an inverter problem. Thanks, I'll do some testing. Ciao.
